spring:
#  mvc:
#    static-path-pattern: /resources/**

  web:
    resources:
      static-locations: [classpath:/public, classpath:/static]
      add-mappings: true       # 静态资源是否生效
      cache:
        period: 11000        # 静态资源缓存周期 单位: 秒


#server.port: 8080
#spring.servlet.multipart.max-file-size: 10MB

#debug: true

#logging:
#  pattern:
#    console: "%green([%-5p]) %boldYellow([%45logger]) - %magenta(%m) %n"
#  level:

#    实体: TRACE