spring:
  # redis 规则
  redis:
    host: 10.1.1.128
    database: 0
    port: 6379
    password: secret
    timeout: 60000 # 连接超时 ms
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1   # 最大阻塞等待时间, 负数表示无限制
        max-idle: 5    # 连接池最大空闲连接
        min-idle: 0    # 连接池最小空闲连接

  # 数据源
  datasource:
    druid:
      url: jdbc:mysql://10.1.1.128:3306/todos?useSSL=false
      username: root
      password: secret