server.port: 8080

spring.servlet.multipart.max-file-size: 10MB

mycar:
  brand: BYD
  price: 100000


#debug: true

#logging:
#  pattern:
#    console: "%green([%-5p]) %boldYellow([%45logger]) - %magenta(%m) %n"
#  level:

#    实体: TRACE